<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Contract\Repository;

use B2W\SkyHub\Contract\Entity\ProductEntityInterface;

/**
 * Interface ProductRepositoryInterface
 * @package B2W\SkyHub\Contract\Repository
 */
interface ProductRepositoryInterface
{
    /**
     * @param array $filter
     * @return mixed
     */
    public function find(Array $filter = []);

    /**
     * @param int|\WP_Post $post
     * @return mixed
     */
    public function one($post);
    /**
     * @param $sku
     * @return ProductEntityInterface
     */
    public function sku($sku);
}
