<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Model\Transformer\Order\Misc;

use B2W\SkyHub\Model\Transformer\EntityToDbAbstract;

class PersonType extends EntityToDbAbstract
{
    protected function _getMapInstance()
    {
        return null;
    }

    public function convert()
    {
        /** TODO MAP PERSON TYPE VALUES IN ADMIN */
        return '';
    }
}
