<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Model\Transformer\Order\Shipment\Track;

use B2W\SkyHub\Model\Entity\Order\Shipment\TrackEntity;
use B2W\SkyHub\Model\Map\Order\Shipment\TrackMap;
use B2W\SkyHub\Model\Transformer\EntityToDbAbstract;

/**
 * Class EntityToDb
 * @package B2W\SkyHub\Model\Transformer\Order\Shipment\Track
 */
class EntityToDb extends EntityToDbAbstract
{
    /**
     * @return TrackMap
     */
    protected function _getMapInstance()
    {
        return new TrackMap();
    }

    /**
     * @return TrackEntity
     */
    public function getEntity()
    {
        return $this->_entity->getShipments()->getTracks();
    }
}
