<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Model\Transformer\Customer\Misc;

use B2W\SkyHub\Model\Transformer\DbToEntityAbstract;

class NameDbToEntity extends DbToEntityAbstract
{
    protected function _getAttributeMap()
    {
        return array();
    }

    public function convert()
    {
        $first = isset($this->_meta['first_name'])
            ? current($this->_meta['first_name'])
            : current($this->_meta['_billing_first_name']);

        $last = isset($this->_meta['last_name'])
            ? current($this->_meta['last_name'])
            : current($this->_meta['_billing_last_name']);

        $this->_parentEntity->setName($first . ' ' . $last);

        return null;
    }
}
