<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Model\Transformer\DateTime;

class ToString
{
    /**
     * @param \DateTime $object
     * @return mixed
     */
    public function convert(\DateTime $object)
    {
        return $object->format('Y-m-d H:i:s');
    }
}
