<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Model\Transformer\Product\PromotionalPrice;

use SkyHub\Api\EntityInterface\Catalog\Product;

/**
 * Class EntityToApi
 * @package B2W\SkyHub\Model\Transformer\Product\PromotionalPrice
 */
class EntityToApi
{
    /**
     * Convert Promotional Price
     *
     * @param $value
     * @param \B2W\SkyHub\Model\Transformer\Product\EntityToApi $parentTranformer
     * @return null
     */
    public function convert($value, \B2W\SkyHub\Model\Transformer\Product\EntityToApi $parentTranformer)
    {
        /** @var Product $productInterface */
        $productInterface = $parentTranformer->getInterface();

        $productInterface->setPromotionalPrice($value ? $value : "");
    }
}
