<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Exception\Api;

use B2W\SkyHub\Exception\Exception;

/**
 * Class OrderNotFoundException
 * @package B2W\SkyHub\Exception\Api
 */
class OrderNotFoundException extends Exception
{
    /**
     * @var string
     */
    protected $message = 'Order not found';
}
