<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Contract\Repository\Product;

/**
 * Interface AttributeRepositoryInterface
 * @package B2W\SkyHub\Contract\Catalog\Product\Attribute
 */
interface AttributeRepositoryInterface
{
    /**
     * @param $code
     * @return mixed
     */
    public function code($code);

    /**
     * @return mixed
     */
    public function all();
}
