<?php

/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace B2W\SkyHub\Helper\Catalog\Product;

use B2W\SkyHub\Contract\Entity\Product\AttributeEntityInterface;

class Attribute
{
    /**
     * @param AttributeEntityInterface $attribute
     * @param $value
     * @return bool|mixed
     */
    public function getOption(AttributeEntityInterface $attribute, $value)
    {
        foreach ($attribute->getOptions() as $option) {
            if ($option->getCode() == $value) {
                return $option;
            }
        }

        return false;
    }
}
